language: cpp
sudo: required
dist: trusty

services:
- docker

git:
  depth: 5

notifications:
  slack:
    secure: bEWPwOoefNXdXqQM1dUUmkBx4MWNJfYMNZPXWDlqxqJCTWoy00SkeH4mTlJSqVPMuQJzqQZ66Q6GK04YEZTLQhobN4tR3Qk9XpzmmE+65TVi4HrGNFJqxGCsPFr5CP4frCiH8rpsyNgwjf76z2a+9XnPYiVWvt0ECZHTeNkdqfHTaJr+TU1URi6iJXQD8C7mCxaYgNcEFfmUb8td17JIvh0dVlYjhh19nRwOxTbJ9QivyHl2MEFMD13CPMUKL1NxOK54Xi1d4cxPVtpJJvYfkRgf+TxJHF2I8BeSmIbE4K8MubbDnotBuipaVEkuZRTFt2wwh7l95u8zIvUbpLUyWHPoS6wKT0wqWe48z68YNf23Lb5TIuVXRtBKmDCNeGLQ4q2Blx8FLX921ugUf7DoquIBJgjeOpiuIPc0l07o3lXp5x6au/mUePfi+iOcXeQRcYN60GDs/Q+zNOOZbfATtg0DTTcPv3rPr1l8MeWlYf4FBCBfVBxzbzjCQEY8CfqajC/5Lc7agEwb3AKh8v3GmSShaZ4WB1vdFtvB9fk5biiAv9dY1U1UEzdK9HLC8+J5OaXdTtwjm4nT7D/Sj8nFqE7opens8WHNVfdzbjP/y7ux7N4O69MEPGumNRSWL4T4JGuShULPt86pzGqh22oUxDtMDbhffnOdlv9Ko6NgtKE=
    #  irc:
    #- "ircs://chat.freenode.net:7070#grangerhub"
  email:
    on_success: change
    on_failure: change

matrix:
  include:
  - os: linux
    env: PLATFORM=linux
    before_install:
    - docker pull wtfbbqhax/tremulous:v3
    - docker run -e PLATFORM -v $(pwd):/usr/src wtfbbqhax/tremulous:v3 ./misc/docker-build.sh
    script:
    - true
  - os: linux
    env: PLATFORM=mingw32
    before_install:
    - docker pull wtfbbqhax/tremulous:v3
    - docker run -e PLATFORM -v $(pwd):/usr/src wtfbbqhax/tremulous:v3 ./misc/docker-build.sh
    script:
    - true
  - os: linux
    env: PLATFORM=mingw32 ARCH=x86
    before_install:
    - docker pull wtfbbqhax/tremulous:v3
    - docker run -e ARCH -e PLATFORM -v $(pwd):/usr/src wtfbbqhax/tremulous:v3 ./misc/docker-build.sh
    script:
    - true
  - os: osx
    osx_image: xcode8
    compiler: clang
    env: ARCH=x86_64
    before_install:
    - brew update
    - brew install freetype --universal
    - rm -rf build
    script:
    - ./misc/travis-ci-build.sh

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: tm8Ie0GVvv7Sdb4vxtewTWGJztrPMSrws9KoXNUHRenbnqujrFusFabef+2YDZbWq2+Ki85ey2SXvYiBWJs3FKVnePc/s2ax0JSVJCUvGntQC1PiD/+xcpWYzy9DACQtqXRdwRx2aURqpj6KXHJACtbo4dUa028xObcwAB1FmIi/SGafUzU0JdyJsggNhFmO+c4hk9Vo6uMXFBrXXhZbMAQT2dFvTqtwX+cWzbMHgCRIXLuevuOpq/oONL6RHQIgErzfLwrnyzbrNt/fftFttZm7blzIKzi4txpI0g5lHEAAgauoYRJngPDfDQtiN0bgTMQNuGhqgf52PKUAr4eZ4QZNn+t/tyLauqRPfPm+m9a7QOYLye34qDhjPt87vYnUUfpdwftCwd5UJs65b3CFNp+grARxU1bRld4DkcyOVKPH4pMQN1nP3FNpmyKNZdFOrq6iq7hrQ7xCfqnL5xuPVIqWJa3cE5qanQsIwHERgyDjEGkwCRjZofAqioCDzSCKBqnTkXVoBczLTm/I4xrsYCnbwfb5cKR3p910wR1IR4JxX2XjIn78vFAlKYr2BOModjLO3oQym76NBOmaf0LO8BP8kJi6q2CxuFGnbK7qlhn8CHJb9vLFh7ZJNeRiGkPSP2lf32xm/MnpFgNuNXGF3mRwxL9M/eKXRaL9feDouYM=
  on:
    repo: wtfbbqhax/tremulous
    tags: true
  file_glob: true
  file: "build/*.zip"
