language: cpp
sudo: required
dist: trusty

git:
    depth: 5

script:
    - ./misc/travis-ci-build.sh

notifications:
    email:
      on_success: change
      on_failure: change

matrix:
  include: 
    - os: linux
      env: USE_RESTCLIENT=1 PLATFORM=mingw32 ARCH=x86_64
      compiler: gcc
      before_install:
        - sudo apt-add-repository ppa:zoogie/sdl2-snapshots -y
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - zoogie/sdl2-snapshots
          packages:
            - libgl1-mesa-dev
            - libsdl2-dev
            - libfreetype6-dev
            - mingw-w64
            - g++-mingw-w64
            - g++-multilib

    - os: linux
      env: USE_RESTCLIENT=1 USE_CODEC_VORBIS=1 USE_FREETYPE=1 ARCH=x86_64
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - zoogie/sdl2-snapshots
          packages:
            - gcc-5
            - g++-5
            - libgl1-mesa-dev
            - libsdl2-dev
            - libfreetype6-dev

    - os: osx
      osx_image: xcode8
      compiler: clang
      env: USE_RESTCLIENT=1 USE_CODEC_VORBIS=1 USE_FREETYPE=1 ARCH=x86_64
      before_install:
        - brew update
        - brew install freetype --universal

    - os: osx
      osx_image: xcode8
      compiler: clang 
      env: USE_RESTCLIENT=1 USE_CODEC_VORBIS=1 USE_FREETYPE=1 ARCH=x86
      before_install:
        - brew update
        - brew install freetype --universal

deploy:
    provider: releases
    skip_cleanup: true
    api_key:
      secure: tm8Ie0GVvv7Sdb4vxtewTWGJztrPMSrws9KoXNUHRenbnqujrFusFabef+2YDZbWq2+Ki85ey2SXvYiBWJs3FKVnePc/s2ax0JSVJCUvGntQC1PiD/+xcpWYzy9DACQtqXRdwRx2aURqpj6KXHJACtbo4dUa028xObcwAB1FmIi/SGafUzU0JdyJsggNhFmO+c4hk9Vo6uMXFBrXXhZbMAQT2dFvTqtwX+cWzbMHgCRIXLuevuOpq/oONL6RHQIgErzfLwrnyzbrNt/fftFttZm7blzIKzi4txpI0g5lHEAAgauoYRJngPDfDQtiN0bgTMQNuGhqgf52PKUAr4eZ4QZNn+t/tyLauqRPfPm+m9a7QOYLye34qDhjPt87vYnUUfpdwftCwd5UJs65b3CFNp+grARxU1bRld4DkcyOVKPH4pMQN1nP3FNpmyKNZdFOrq6iq7hrQ7xCfqnL5xuPVIqWJa3cE5qanQsIwHERgyDjEGkwCRjZofAqioCDzSCKBqnTkXVoBczLTm/I4xrsYCnbwfb5cKR3p910wR1IR4JxX2XjIn78vFAlKYr2BOModjLO3oQym76NBOmaf0LO8BP8kJi6q2CxuFGnbK7qlhn8CHJb9vLFh7ZJNeRiGkPSP2lf32xm/MnpFgNuNXGF3mRwxL9M/eKXRaL9feDouYM=
    on:
      tags: true
    file_glob: true
    file: "build/*.zip"

# _____ _   _  ____ _  __
#|  ___| | | |/ ___| |/ /
#| |_  | | | | |   | ' / 
#|  _| | |_| | |___| . \ 
#|_|    \___/ \____|_|\_\
#

#    - os: linux
#      env: PLATFORM=mingw32 ARCH=x86
#      compiler: gcc
#      before_install:
#      - sudo apt-add-repository ppa:zoogie/sdl2-snapshots -y
#      - sudo dpkg --add-architecture i386
#      - sudo apt-get update
#      - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes upgrade gcc-multilib g++-multilib mingw-w64 mingw-w64 gcc-mingw-w64 g++-mingw-w64 libgl1-mesa-dev libsdl2-dev libfreetype6-dev
#      addons:
#        apt:
#          sources:
#          - ubuntu-toolchain-r-test

#    - os: linux
#      env: USE_CODEC_VORBIS=1 USE_FREETYPE=1 ARCH=x86
#      compiler: gcc
#      addons:
#        apt:
#          sources:
#          - ubuntu-toolchain-r-test
#          - zoogie/sdl2-snapshots
#          packages:
#          - gcc-5-multilib
#          - g++-5-multilib
#          - libgl1-mesa-dev
#          - libsdl2-dev
#          - libfreetype6-dev


