language: cpp
sudo: required
dist: trusty
services:
- docker
git:
  depth: 5
notifications:
  slack:
    secure: bEWPwOoefNXdXqQM1dUUmkBx4MWNJfYMNZPXWDlqxqJCTWoy00SkeH4mTlJSqVPMuQJzqQZ66Q6GK04YEZTLQhobN4tR3Qk9XpzmmE+65TVi4HrGNFJqxGCsPFr5CP4frCiH8rpsyNgwjf76z2a+9XnPYiVWvt0ECZHTeNkdqfHTaJr+TU1URi6iJXQD8C7mCxaYgNcEFfmUb8td17JIvh0dVlYjhh19nRwOxTbJ9QivyHl2MEFMD13CPMUKL1NxOK54Xi1d4cxPVtpJJvYfkRgf+TxJHF2I8BeSmIbE4K8MubbDnotBuipaVEkuZRTFt2wwh7l95u8zIvUbpLUyWHPoS6wKT0wqWe48z68YNf23Lb5TIuVXRtBKmDCNeGLQ4q2Blx8FLX921ugUf7DoquIBJgjeOpiuIPc0l07o3lXp5x6au/mUePfi+iOcXeQRcYN60GDs/Q+zNOOZbfATtg0DTTcPv3rPr1l8MeWlYf4FBCBfVBxzbzjCQEY8CfqajC/5Lc7agEwb3AKh8v3GmSShaZ4WB1vdFtvB9fk5biiAv9dY1U1UEzdK9HLC8+J5OaXdTtwjm4nT7D/Sj8nFqE7opens8WHNVfdzbjP/y7ux7N4O69MEPGumNRSWL4T4JGuShULPt86pzGqh22oUxDtMDbhffnOdlv9Ko6NgtKE=
  irc:
  - ircs://chat.freenode.net:7070#grangerhub
  email:
    on_success: change
    on_failure: change
matrix:
  include:
  - os: linux
    env: PLATFORM=linux
    before_install:
    - docker pull wtfbbqhax/tremulous:v3
    - docker run -e PLATFORM -v $(pwd):/usr/src wtfbbqhax/tremulous:v3 ./misc/docker-build.sh
    script:
    - true
  - os: linux
    env: PLATFORM=linux ARCH=x86
    before_install:
    - docker pull wtfbbqhax/tremulous:v3
    - docker run -e PLATFORM -e ARCH -v $(pwd):/usr/src wtfbbqhax/tremulous:v3 ./misc/docker-build.sh
    script:
    - true
  - os: linux
    env: PLATFORM=mingw32
    before_install:
    - docker pull wtfbbqhax/tremulous:v3
    - docker run -e PLATFORM -v $(pwd):/usr/src wtfbbqhax/tremulous:v3 ./misc/docker-build.sh
    script:
    - true
  - os: linux
    env: PLATFORM=mingw32 ARCH=x86
    before_install:
    - docker pull wtfbbqhax/tremulous:v3
    - docker run -e PLATFORM -e ARCH -v $(pwd):/usr/src wtfbbqhax/tremulous:v3 ./misc/docker-build.sh
    script:
    - true
  - os: osx
    osx_image: xcode8
    compiler: clang
    env: ARCH=x86_64
    before_install:
    - brew update
    - brew install freetype --universal
    - rm -rf build
    script:
    - ./misc/travis-ci-build.sh

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: MwLyENzULs7pfeweqR/QoO+je3t+2I5tNTrgE2ed7+ZJirzuZe0EVYD+HDIfh7Yn6NHBhlYmXhFBMCJ6rhF6Zz4xHvEZh02m/MhCjvkHwkW+sH4/yZWM0klCAkn1iKygOPiOAXX7JFUEdj0Ct6uB8eJYfAEztgg0jqlPcx3EZ36Ow6RqmN9/YPcI7TcRiKwL9mUa/Q/y9sC6kOspLQW0RkB3sqmakbck5KCuAxGZ5VtXbKXmbFHpbLsxZzarzb+HqKfdQqMEUJN4dukxIgQxFHiIIrpE/I9dQ5KJ5UVV3/YzQfeg3ReEbf7ol1tXevoua7ozAA2cOKrNDnZo4ATJc1C7nHbdsNmc0aRJqu2YSaRk/qWZNURp2cvYTQPFTht91kSnmM799tof2tMHMee4Ky4EiO1oI+WQ2i0euXwgYz2PfxF8OWgorPRflr5JKao0qb1TiX7RAC7jSGQ8u6GtcaCCdS7t7vbWdkH5Jg/EX97HZ4QU84P/3PjSEeyeEMv8SLyGLwDT9tf4cV3sgljFKoubXRt5UZ1rXNHwuOkO9WP44gVd+BCTXja6oTJ57nfvu30W2mYQzR6YsM+f+FsJBrd8ldT7S7vtzy5LYHelZ+lQIYtE+J2eej4nNaUN+TSESCGAA1z9Zme6KH6Z26+Q7dQwyONO6q9zW5ps6AuZ/lw=
  file_glob: true
  file: build/*.zip
  on:
      tags: true
